os: linux
sudo: false
language: python
python:
  - 3.6

env:
  global:
    - CC_TEST_REPORTER_ID=5fa0ac042b1c809aeefa5ed9dcebaaf2c4ba503a520081bde94f39c99fc2aeb8

install:
  - pip install -r requirements-dev.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  - pip

notifications:
  - email: false
